### ISSUE TITLE
Create New Apps

### ISSUE THREAD

**Issue by partisani** [SnakerCZ/debios#1]
# Creating New Apps On DebiOS

### .debiapp is a file extension like .bat

**Comment by debios** [comment]
hey there

yes, the entire system, includin debiapps, has been made in batch, so you could theoretically write apps in batch for it, tho i still haven't created any real interface for custom build apps (there was in previous versions of debios, but it was very primitive and removed for long time), so you can't call them unless you code the system to do so. i **might** add some simple call commands for custom apps later (tho the main goal is creating a system app, which would serve the purpose of an app store and would download apps safely from official database)
