### ISSUE TITLE
can i use some code?

### ISSUE THREAD

**Issue by thebobmaker** [SnakerCZ/debios#5]
At school rn, so this i smy alt. i am about to remake my batch os, but when i try to attempt some features, it doesnt work.
(my project is coffee os).
so, can i borrow code?

**Comment by debios** [comment]
Hey, no problems, just credit me if you publish it somewhere! :)
Use whatever you need, I’ve done that a lot as well while creating DebiOS.

Odesláno z iPhonu

21. 2. 2023 v 2:11, thebobmaker ***@***.***>:

﻿

At school rn, so this i smy alt. i am about to remake my batch os, but when i try to attempt some features, it doesnt work.
(my project is coffee os).
so, can i borrow code?

**Comment by jibjobjeffrey** [comment]
main here, I am remaking my batch os so it is like DOS, with some things like custom extensions and a download.

**Comment by Microgoht** [comment]
how code this os?
